server:
  port: 8021


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: ribbon-client

management:
  endpoints:
    web:
      exposure:
        include: "*"